### ISSUE TITLE
can players use Flint and Steel and cake on map?

### ISSUE THREAD

**Issue by XiangZhao969** [AndreTheGamer/SurvivalGame#57]
and after matchs, maps will be reset. likes in lbsg

**Comment by xZeroMCPE** [comment]
Yes, they can.

**Comment by XiangZhao969** [comment]
cool. how can i edit the number of pods?

**Comment by xZeroMCPE** [comment]
If you are looking towards on a better version of SurvivalGame please try BukkitPE it's a MCPE SERVER Software with better stable features use it instead of pocketmine Visit the github or site to learn how to install , You can also download SurvivalGame for BukkitPE via BukkitPE Website/plugin section

GitHub: ww.github.com/bukkitpe/bukkitpe
Site: www.bukkitpe.net
plugins: forums.bukkitpe.net   then click plugins

You can get help, support and request new plugins via the site. Thanks

**Comment by XiangZhao969** [comment]
ok, just one last question :v what is the different between this plugin and the old fsg?

**Comment by xZeroMCPE** [comment]
Many features such as:
- Better sign format
- Supports up to 24 players
- Ability to changed ChatPrefix
- Anti Advertising blocker
- Stops spams
- And more\* Check out BukkitPE plugin section (look for SG there), it's where mainly some features will be added there.
